# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: go mod download
    - name: Build
      run: go build -o ./bin/wallet-service ./cmd/wallet-service
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Create container
      uses: docker/build-push-action@v3.2.0
      with:
        load: true
        tags: imigaka/wallet-service
        context: .
        file: ./Dockerfile
    - run: docker push imigaka/wallet-service
  
  deploy:  
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/sovkom-hac-backend/sovkom-wallet-service
            git pull origin main
            git status
            make down
            make run
